### ISSUE TITLE
Picture Path in Backend

### ISSUE THREAD

**Issue by BishankAnonymous** [hoot-doot/RMS#1]
The picturepath in the database doesn't match picturepath in the express endpoint
https://github.com/hoot-doot/RMS/blob/c9dac53d160c4535e839ee737cdab8dce1a91c39/server/index.js#L74-L79

https://github.com/hoot-doot/RMS/blob/c9dac53d160c4535e839ee737cdab8dce1a91c39/server/index.js#L297-L301

**Comment by RomanKumarShahi** [comment]
Issue has been fixed 
const picturePath = req.file.path;
const picture = path.basename(picturePath);
