### ISSUE TITLE
No Icon

### ISSUE THREAD

**Issue by BishankAnonymous** [hoot-doot/RMS#6]
Icon imported as PeopleOutlinedIcon referenced as PeopleOutlined

https://github.com/hoot-doot/RMS/blob/c9dac53d160c4535e839ee737cdab8dce1a91c39/client/src/scenes/global/Sidebar.jsx#L9

https://github.com/hoot-doot/RMS/blob/c9dac53d160c4535e839ee737cdab8dce1a91c39/client/src/scenes/global/Sidebar.jsx#L175

**Comment by hoot-doot** [comment]
fixed icon is PeopleOutlinedIcon  as imported now
